### ISSUE TITLE
Add better logging

### ISSUE THREAD

**Issue by kenmoini** [kenmoini/pilot-light#6]
Ability to log to multiple standard facilities, eg:

```
pilot_light:
  logging:
    - mode: stdout
      sinks:
        - name: sys_stdout
          target: stdout
        - name: file_stdout
          target: /var/log/pilot-light.log
    - mode: stderr
      sinks:
        - name: sys_stderr
          target: stderr
        - name: file_stderr
          target: /var/log/pilot-light-errors.log
```

Or something, idk, how does journald work again?
